# Generated by Django 2.2 on 2019-05-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityBroker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('host', models.CharField(max_length=30)),
                ('port', models.IntegerField()),
                ('cred_username', models.CharField(max_length=20, null=True)),
                ('cred_password', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
